# Generated by Django 5.1 on 2024-09-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAreas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_areas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('award', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ganison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('answers', models.CharField(max_length=100)),
                ('correct_answers', models.CharField(max_length=100)),
                ('question_number', models.IntegerField()),
                ('subject_contents', models.CharField(max_length=100)),
                ('assessment_areas', models.CharField(max_length=100)),
                ('sydney_correct_count_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sydney_average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sydney_participants', models.IntegerField()),
                ('student_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_total_assessed', models.IntegerField()),
                ('student_area_assessed_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_area_assessed_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('participant', models.IntegerField()),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('school_percentile', models.IntegerField()),
                ('sydney_percentile', models.IntegerField()),
                ('strength_status', models.CharField(max_length=100)),
                ('high_distinct_count', models.IntegerField()),
                ('distinct_count', models.IntegerField()),
                ('credit_count', models.IntegerField()),
                ('participant_count', models.IntegerField()),
                ('award', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('subject_contents', models.CharField(max_length=100)),
            ],
        ),
    ]
